  # Specify the directory for the frontend build output
  publish = "client/dist"
  # Command to build the frontend
  command = "npm run build --prefix client"

# Redirect API requests to the backend
[[redirects]]
  from = "/api/*"
  to = "https://crm-grocery.onrender.com/:splat" 
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
